baseURL = 'https://aramide.dev'
languageCode = 'en-US'
title = 'Tobiloba Ogundiyan'
theme = 'rusty-typewriter'



[params.rtwt.home]
showAuthorImg = false
sidePaneTags = true
showFeatured = true
showRecent = true
hideRecentWhenFeatured = true
countRecent = 7

[params.rtwt.side.home]
sidePaneSticky = true
taxonomies = ['tags', 'series']
countTaxonomy = 4

[params.rtwt.side.list]
sidePaneSticky = false

[params.rtwt.side.single]
sidePaneSticky = true
showDetails = true
showTableOfContents = true
showAttachments = true
showRelated = true
countRelated = 5

[taxonomies]
tag = 'tags'
series = 'series'

[params.author]
name = 'Tobiloba Ogundiyan'

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 1

[[menus.main]]
name = 'Writings'
pageRef = '/writings'
weight = 1


[[menus.main]]
name = 'About'
pageRef = '/about-tobiloba-aramide-ogundiyan.md'
weight = 3


# search related stuff ================
[outputFormats]
[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
notAlternative = true

[mediaTypes]
[mediaTypes."application/json"]
suffixes = ["json"]

[outputs]
home = ["HTML", "RSS", "SearchIndex"]

[markup.goldmark.renderer]
unsafe = true
